### ISSUE TITLE
 xfer_in_disk: Read size does not match: Input/output error (-1, 131072) (5) 0x7f26dad54010

### ISSUE THREAD

**Issue by jiverson002** [jliverson5/sbma#3]
Steps to reproduce:

```
bdmprun -ns=6 -nr=1 -pg=4 -rm=910000 -sbma=osvmm -wd=/scratch/bdmp parmetis /data/graphs/nlpkkt240.graph 1 6 0 0 7 0
```

```
bdmprun -ns=6 -nr=1 -pg=4 -rm=910000 -sbma=aggrd -wd=/scratch/bdmp parmetis /data/graphs/nlpkkt240.graph 1 6 0 0 7 0
```

**Comment by jliverson5** [comment]
Looks like parmetis just needed to be recompiled.

**Comment by jiverson002** [comment]
In these cases, errno = EIO. This suggests a low-level I/O error. To debug, EIO is allowed and causes a re-execution of the operation. I believe this error may be due to a failing disk. Confirm this by disk checking (e2fsck) drive and testing on other machines.

**Comment by jiverson002** [comment]
Confirmed there were bad sectors on drive. Program completed successfully on a different machine. This suggests hardware problem, not software problem.
